import Head from 'next/head';
import { GlobalButton } from '../globalStyles';
import styles from '../styles/Home.module.css';
import { Navbar } from '../components';
import Link from 'next/link';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Github Explorer</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <h1>
        Explore more about{' '}
        <Link href='/user/summary'>
          <a>your profile!</a>
        </Link>
      </h1>
    </div>
  );
}
