import Head from 'next/head';
import { useContext } from 'react';
import { Navbar, Repos, SearchUser, User, UserInfo } from '../components';
import { StateContext } from '../context/context';

export default function Home() {
  const {
    state: { isLoading },
  } = useContext(StateContext);
  console.log(isLoading);
  if (isLoading) {
    return (
      <main>
        <Head>
          <title>Github Explorer</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <Navbar />
        <SearchUser />
        <h1 className='text-xl'>Loading...</h1>
      </main>
    );
  }
  return (
    <main>
      <Head>
        <title>Github Explorer</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <SearchUser />
      <UserInfo />
      <User />
      <Repos />
    </main>
  );
}
